### PR TITLE
remove popup paywall window when shown

### PR DESCRIPTION
**Pull request by Adidi**
The site showing now a popup paywall in every page if you not logged in - this PR removes it

Best

### CODE REVIEW

**Review by Adidi — COMMENTED** [review]
.

**Comment by rotembcohen** [comment]
Awesome. Thanks!

**Review by rotembcohen — APPROVED** [review]

**Comment by Adidi** [comment]
Why don't I see the changes in the repo ?

**Review by rotembcohen — COMMENTED** [review]
checking

**Comment by rotembcohen** [comment]
should be fine now. sorry, forgot to merge.

**Pull request merged**
